### ISSUE TITLE
addMapboxGL() not working on Windows

### ISSUE THREAD

**Issue by behrman** [rstudio/leaflet.mapboxgl#2]
The following code worked when tested on a Mac, but not on Windows.

``` r
library(dplyr)
library(leaflet)
library(leaflet.mapboxgl)

access_token <- "redacted"
style_url <- "mapbox://styles/stanford-datalab/cjsqj3qvi3zrf1fld8qvywggs"

leaflet(width = 950, height = 800)  %>% 
  addMapboxGL(
    accessToken = access_token,
    style = style_url
  )
```

**Comment by jcheng5** [comment]
If you're using RStudio 1.1.x, can you try RStudio 1.2.x instead? https://www.rstudio.com/products/rstudio/download/preview/

I suspect RStudio 1.1 on Windows and Linux doesn't support WebGL, as it uses a pretty dated version of WebKit (whereas RStudio 1.1 on Mac uses Safari).

**Comment by behrman** [comment]
That may explain it. Our Mac students are using RStudio 1.2.x, and our Windows students are using 1.1.x.

The reason for the later is that the Pandoc included with 1.2.x was causing knitting problems for our Windows students. We have another quarter starting in 3 weeks. Has the Pandoc in 1.2.x been updated since Jan? The current version is 2.7.

**Comment by behrman** [comment]
One of our students with Windows installed the latest RStudio 1.2.1322 and tried running the above code. The resulting window as all grey, and the zoom button was greyed out. There were no error messages.

**Comment by yihui** [comment]
The current latest preview version of RStudio (1.2.1322) contains Pandoc 2.6. I just test your example on Windows (7) and was not able to reproduce the issue that your student reported. Everything looked okay in the RStudio Viewer.

> The reason for the later is that the Pandoc included with 1.2.x was causing knitting problems for our Windows students.

If they are using an earlier version of 1.2.x, I recommend that they upgrade to at least 1.2.1322 because previous versions of 1.2.x bundled Pandoc 2.5, which was known to have some bad issues (https://github.com/rstudio/rstudio/pull/4274). Check `rmarkdown::pandoc_version()` in the R console and make sure it is at least 2.6.

**Comment by jcheng5** [comment]
I suspect what is happening is that Mapbox GL JS will only work if RStudio is running in hardware-accelerated mode. If you go to Tools | Global Options | General | Advanced, there's a "Rendering Engine" option which defaults to Auto-Detect. Can they try with Desktop OpenGL?

(Tip: If that causes RStudio to behave so badly that they can't even get the setting switched back to the default, you can hold down the Ctrl key as RStudio starts up, and that will pop open a dialog letting you customize this setting at start time.)

**Comment by behrman** [comment]
@jcheng5 You were right. The problem was with RStudio's Rendering Engine Auto-Detect on Windows not setting to hardware-accelerated mode. When we manually set this to Desktop OpenGL, everything worked fine. Thanks!

@yihui The Windows student who installed the latest RStudio 1.2 with Pandoc 2.6 still had fatal errors when trying to knit documents, so she had to downgrade back to RStudio 1.1. This is a problem that all of our Windows students encountered, so they're all using 1.1. When do you anticipate RStudio moving to Pandoc 2.7?

**Comment by yihui** [comment]
@behrman I don't know when we will upgrade Pandoc again, but if Pandoc 2.7 solves the problem, you can install Pandoc separately, and **rmarkdown** should use it automatically (it finds the highest version of Pandoc in the system if multiple versions are installed).

**Comment by behrman** [comment]
@yihui I didn't know that thanks. We'll give that a try.

@jcheng5 and @yihui I think we're good to go now. Many thanks for all of your help!
